/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:6a86d2b2-c6fd-4a95-aead-3f1ed79ce5d2",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_8GOs50gXK",
    "aws_user_pools_web_client_id": "5obgnk6l34dtol88r96r6k42mu",
    "oauth": {}
};


export default awsmobile;
