apiVersion: v1
kind: Service
metadata:
  name: fit5225
  labels:
    app: fit5225
spec:
  type: NodePort
  selector:
    app: fit5225
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 5000
      nodePort: 30001
